version: '3.8'

services:
  orpheus:
    build:
      context: ./client
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    tty: true
    ports:
      - '8081:8081'
    volumes:
      - ./client:/orpheus/app:delegated
      - ./client/package.json:/orpheus/package.json
      - ./client/package-lock.json:/orpheus/package-lock.json
    healthcheck:
      disable: true
  server:
    build: ./server
    environment:
      - NODE_ENV=development
    tty: true
    ports:
      - '5002:5002'
    volumes:
      - ./server:/server/app:delegated
      - ./server/package.json:/server/package.json
      - ./server/package-lock.json:/server/package-lock.json
    healthcheck:
      disable: true

volumes:
  notused: